package com.joefkelley.matrix;

public class MatrixElement {
	
	public final int row;
	public final int col;
	public final double value;
	
	public MatrixElement(int row, int col, double value) {
		this.row = row;
		this.col = col;
		this.value = value;
	}
	
	@Override
	public String toString() {
		return "MatrixElement(" + row + "," + col + "," + value + ")";
	}

	// Auto-generated by eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + col;
		result = prime * result + row;
		long temp;
		temp = Double.doubleToLongBits(value);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	// Auto-generated by eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MatrixElement other = (MatrixElement) obj;
		if (col != other.col)
			return false;
		if (row != other.row)
			return false;
		if (Double.doubleToLongBits(value) != Double
				.doubleToLongBits(other.value))
			return false;
		return true;
	}
	
}
